ironandblood/game/urls.py
from django.conf.urls import url

from . import views

USERNAME_REGEX = '[a-zA-Z0-9._]+'

app_name = 'game'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    # Exchanges page
    url(r'^exchanges$', views.exchanges, name='exchanges'),
    url(r'^exchanges/0/(?P<state>[WARC]+)', views.exchanges, name='filter_exchanges'),
    url(r'^exchanges/0/', views.exchanges, name='filter_exchanges_without_opts'),
    # Modify an exchange
    url(r'^exchanges/(?P<exchange_pk>[0-9]+)', views.update_exchange, name='update_exchange'),
    # Exchanges with a user page
    url(r'^exchanges/(?P<offeree>'+USERNAME_REGEX+')/$', views.new_exchange, name='exchange'),
    url(r'^exchanges/(?P<offeree>'+USERNAME_REGEX+')/0/(?P<state>[WARC]+)$', views.new_exchange, name='filter_exchanges_offer'),
    url(r'^exchanges/(?P<offeree>'+USERNAME_REGEX+')/0/$', views.new_exchange, name='filter_exchanges_offer_without_opts'),
    # Bonds page
    url(r'^bonds$', views.bonds, name='bonds'),
    url(r'^bonds/0/(?P<state>[WPF]+)', views.bonds, name='filter_bonds'),
    url(r'^bonds/0/', views.bonds, name='filter_bonds_without_opts'),
    # Modify a Bond
    url(r'^bonds/(?P<bond_pk>[0-9]+)', views.update_bond, name='update_bond'),
    # Exchanges with a user page
    url(r'^bonds/(?P<username>'+USERNAME_REGEX+')/$', views.bond_by_user, name='bond'),
    url(r'^bonds/(?P<username>.+)/0/(?P<state>[WPF]+)', views.bond_by_user, name='filter_bonds_offer'),
    url(r'^bonds/(?P<username>.+)/0/$', views.bond_by_user, name='filter_bonds_offer_without_opts'),
    # Login/Logout
    url(r'^login$', views.login_view, name='login'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^profile$', views.profile, name='profile'),
]

ironandblood/ironandblood/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('game.urls')),
]

admin.site.site_header = 'Iron & Blood administration'
admin.site.site_title = 'Iron & Blood administration'

ironandblood/game/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from .models import Exchange, Resources, Territory, Bond
from .widgets import KnobInput

class ExchangeForm(forms.Form):
  offeror_as_bond = forms.BooleanField(label = 'As Bond?',
    initial = False, required = False,
    widget = forms.CheckboxInput(attrs = {
      'data-size': 'mini',
      'data-on-text': 'Yes',
      'data-on-color': 'warning',
      'data-off-text': 'No',
    }))
  offeree_as_bond = forms.BooleanField(initial = False, required = False,
    widget = forms.CheckboxInput(attrs = {
      'data-size': 'mini',
      'data-on-text': 'Yes',
      'data-on-color': 'warning',
      'data-off-text': 'No',
    }))

  offeror_currency = forms.IntegerField(label = 'Currency',
    widget = KnobInput(color = Resources.color('currency')))
  offeree_currency = forms.IntegerField(
    widget = KnobInput(color = Resources.color('currency')))

  offeror_manufactured = forms.IntegerField(label = 'Manufactured Goods',
    widget = KnobInput(color = Resources.color('manufactured')))
  offeree_manufactured = forms.IntegerField(
    widget = KnobInput(color = Resources.color('manufactured')))

  offeror_agricultural = forms.IntegerField(label = 'Agricultural Goods',
    widget = KnobInput(color = Resources.color('agricultural')))
  offeree_agricultural = forms.IntegerField(
    widget = KnobInput(color = Resources.color('agricultural')))

  offeror_bond = forms.IntegerField(label = 'Bond #', required=False,
    widget = forms.NumberInput(attrs = {
      'style': 'width: 50px'
    }))
  offeree_bond = forms.IntegerField(required=False,
    widget = forms.NumberInput(attrs = {
      'style': 'width: 50px'
    }))

  def __init__(self, offeror, offeree, *args, **kwargs):
    super(forms.Form, self).__init__(*args, **kwargs)

    resource = lambda u, name: getattr(u.player.resources, name)

    self.update('offeror_currency', 'data-max',
      max(resource(offeror, 'currency'), 100) * 3)
    self.update('offeree_currency', 'data-max',
      max(resource(offeree, 'currency'), 100) * 3)

    self.update('offeror_manufactured', 'data-max',
      max(resource(offeror, 'manufactured'), 10) * 3)
    self.update('offeree_manufactured', 'data-max',
      max(resource(offeree, 'manufactured'), 10) * 3)

    self.update('offeror_agricultural', 'data-max',
      max(resource(offeror, 'agricultural'), 10) * 3)
    self.update('offeree_agricultural', 'data-max',
      max(resource(offeree, 'agricultural'), 10) * 3)

  def update(self, field_name, attr, value):
    self.fields[field_name].widget.attrs[attr] = value

  def build_and_offer(self, offeror, offeree, id_offeror_territory,
    id_offeree_territory):
    offeror_res = Resources(
        currency = self.cleaned_data['offeror_currency'],
        agricultural = self.cleaned_data['offeror_agricultural'],
        manufactured = self.cleaned_data['offeror_manufactured'])
    offeror_res.save()
    offeree_res = Resources(
        currency = self.cleaned_data['offeree_currency'],
        agricultural = self.cleaned_data['offeree_agricultural'],
        manufactured = self.cleaned_data['offeree_manufactured'])
    offeree_res.save()

    offeror_territory = None
    if id_offeror_territory:
      offeror_territory = Territory.objects.get(name = id_offeror_territory.split(' (')[0])

    offeree_territory = None
    if id_offeree_territory:
      offeree_territory = Territory.objects.get(name = id_offeree_territory.split(' (')[0])

    offeror_bond = None
    if self.cleaned_data['offeror_bond']:
      try:
        offeror_bond = Bond.objects.get(pk=self.cleaned_data['offeror_bond'])
      except Bond.DoesNotExist:
        raise ValidationError(_("Invalid Bond number."))

    offeree_bond = None
    if self.cleaned_data['offeree_bond']:
      try:
        offeree_bond = Bond.objects.get(pk=self.cleaned_data['offeree_bond'])
      except Bond.DoesNotExist:
        raise ValidationError(_("Invalid Bond number."))

    try:
      exch = Exchange(
        offeror = offeror,
        offeror_resources = offeror_res,
        offeror_territory = offeror_territory,
        offeror_bond = offeror_bond,
        offeror_as_bond = self.cleaned_data['offeror_as_bond'],
        offeror_as_bond_maturity = 0,
        offeree = offeree,
        offeree_resources = offeree_res,
        offeree_territory = offeree_territory,
        offeree_bond = offeree_bond,
        offeree_as_bond = self.cleaned_data['offeree_as_bond'],
        offeree_as_bond_maturity = 0
        )
      exch.offer(user = offeror)
    except Exception as e:
      offeror_res.delete()
      offeree_res.delete()
      raise e

ironandblood/game/views.py
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.csrf import csrf_protect

from .models import Player, Resources, Territory, Exchange, Bond

from .forms import ExchangeForm

def build_context(request, context = {}):
  """
  Build a context dictionary with information for the base html page.
  """
  ctx = {
    'waiting_exchanges': Exchange.objects.filter(offeree = request.user,
      state = Exchange.WAITING),
    'pending_bonds': Bond.objects.filter(borrower = request.user,
      state = Bond.PENDING),
  }
  ctx.update(context)
  return ctx

@login_required(login_url='game:login')
@csrf_protect
def bonds(request, state=Bond.PENDING):
  rb = Bond.objects.filter(holder = request.user).order_by('-pk')
  sb = Bond.objects.filter(borrower = request.user).order_by('-pk')

  states = list(state)
  rb = rb.filter(state__in = states)
  sb = sb.filter(state__in = states)

  return render(request, 'game/bonds.html', build_context(request, {
    'users': User.objects.all(),
    'as_holder_bonds': rb,
    'as_borrower_bonds': sb,
    'states': states
  }))

@login_required(login_url='game:login')
def update_bond(request, bond_pk):
  if request.POST:
    pay = 'pay' in request.POST
    forgive = 'forgive' in request.POST
    valid = pay ^ forgive
    if valid:
      try:
        bond = Bond.objects.get(pk = bond_pk)
        if pay:
          bond.pay(user=request.user)
          messages.success(request, _('Bond paid!'))
        elif forgive:
          bond.forgive(user=request.user)
          messages.info(request, _('Bond forgiven.'))
        else:
          raise ValidationError(_('Unknown operation.'))
      except ValidationError as e:
        if e.params:
          messages.error(request, e.message % e.params)
        else:
          messages.error(request, e.message)
  return HttpResponseRedirect(reverse('game:bonds'))

@login_required(login_url='game:login')
def bond_by_user(request, username, state=Bond.PENDING):
  user = User.objects.get(username = username)
  users = [request.user, user]
  bonds_history = Bond.objects.filter(holder__in = users,
    borrower__in = users)

  states = list(state)
  bonds_history = bonds_history.filter(state__in = states)

  return render(request, 'game/bond_by_user.html', build_context(request, {
    'user': user,
    'bonds_history': bonds_history,
    'states': states
    }))

@login_required(login_url='game:login')
@csrf_protect
def exchanges(request, state=Exchange.WAITING):
  re = Exchange.objects.filter(offeree = request.user).order_by('-offer_date')
  se = Exchange.objects.filter(offeror = request.user).order_by('-offer_date')

  states = list(state)
  re = re.filter(state__in = states)
  se = se.filter(state__in = states)

  return render(request, 'game/exchanges.html', build_context(request, {
    'users': User.objects.all(),
    'received_exchanges': re,
    'sent_exchanges': se,
    'states': states
  }))

@login_required(login_url='game:login')
def update_exchange(request, exchange_pk):
  if request.POST:
    accept = 'accept' in request.POST
    reject = 'reject' in request.POST
    cancel = 'cancel' in request.POST
    valid = accept ^ reject ^ cancel
    if valid:
      try:
        exch = Exchange.objects.get(pk = exchange_pk)
        if accept:
          exch.accept(user=request.user)
          messages.success(request, _('Exchange accepted!'))
        elif reject:
          exch.reject(user=request.user)
          messages.info(request, _('Exchange rejected.'))
        elif cancel:
          exch.cancel(user=request.user)
          messages.info(request, _('Exchange canceled.'))
        else:
          raise ValidationError(_('Unknown operation.'))
      except ValidationError as e:
        if e.params:
          messages.error(request, e.message % e.params)
        else:
          messages.error(request, e.message)
  return HttpResponseRedirect(reverse('game:exchanges'))

@login_required(login_url='game:login')
def new_exchange(request, offeree, state=Exchange.WAITING):
  offeree_obj = User.objects.get(username = offeree)
  form = ExchangeForm(request.user, offeree_obj, request.POST or None)
  error_message = None
  if form.is_valid():
    try:
      id_offeror_territory = request.POST['id_offeror_territory']
      id_offeree_territory = request.POST['id_offeree_territory']
      resource = form.build_and_offer(request.user, offeree_obj,
        id_offeror_territory = id_offeror_territory,
        id_offeree_territory = id_offeree_territory)
    except ValidationError as e:
      if e.params:
        messages.error(request, e.message % e.params)
      else:
        messages.error(request, e.message)
    else:
      messages.success(request, _('Exchange offer sent!'))
      return HttpResponseRedirect(reverse('game:exchanges'))
  users = [request.user, offeree_obj]
  exchange_history = Exchange.objects.filter(offeror__in = users,
    offeree__in = users)

  states = list(state)
  exchange_history = exchange_history.filter(state__in = states)

  return render(request, 'game/new_exchange.html', build_context(request, {
    'form': form,
    'offeree': offeree_obj,
    'territories': Territory.objects.all(),
    'exchange_history': exchange_history,
    'states': states
    }))

@login_required(login_url='game:login')
def home(request):
  territories = Territory.objects.all()
  users = User.objects.all()
  colors = ['#659BA3', '#725E54', '#FFEBB5', '#996982', '#01704B']
  dct = dict()
  for t in territories:
    dct[t.code] = colors[t.owner.pk % len(colors)]
  user_legend = dict()
  for u in users:
    user_legend[u.username] = colors[u.pk % len(colors)]
  return render(request, 'game/home.html', build_context(request, {
    'colors': dct,
    'colors_legend': user_legend
  }))

@login_required(login_url='game:login')
def logout_view(request):
  logout(request)
  return redirect(reverse('game:login'))

def login_view(request):
  state = _("Please log in above.")
  alert_type = 'info'
  username = password = ''
  if request.POST:
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
      if user.is_active:
        login(request, user)
        return redirect(request.GET.get('next', '/'))
      else:
        alert_type = 'danger'
        state = _("Your account is not active, please contact the site admin.")
    else:
      alert_type = 'danger'
      state = _("Your username and/or password were incorrect.")
  context = {'alert_type': alert_type, 'state': state, 'username': username}
  return render_to_response('game/login.html', RequestContext(request, context))

@login_required(login_url='game:login')
def profile(request):
  return render(request, 'game/home.html', {})

ironandblood/game/templates/game/bonds.html
{% extends 'game/base.html' %}
{% load staticfiles i18n game_tags %}

{% block append_head %}
<link href="{% static 'game/css/icheck/flat/green.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="row">
 <div class="col-md-6 col-sm-6 col-xs-12">
  <div class="x_content">
   <div class="btn-group" data-toggle="buttons">
     <label id="filter_open" class="btn btn-primary-outline btn-sm{% if 'W' in states %} active{% endif %}">
       <input name="filter_opts_pending" type="checkbox"{% if 'W' in states %} checked{% endif %}> {% trans 'Pending' %}
     </label>
     <label class="btn btn-primary-outline btn-sm{% if 'P' in states %} active{% endif %}">
       <input name="filter_opts_paid" type="checkbox"{% if 'P' in states %} checked{% endif %}> {% trans 'Paid' %}
     </label>
     <label class="btn btn-primary-outline btn-sm{% if 'F' in states %} active{% endif %}">
       <input name="filter_opts_forgiven" type="checkbox"{% if 'F' in states %} checked{% endif %}> {% trans 'Forgiven' %}
     </label>
     <a href="#" id="filter_bonds" class="btn btn-primary btn-sm" role="button">Filter</a>
   </div>
  </div>
 </div>
</div>

<div class="row">
 <div class="col-md-6 col-sm-6 col-xs-12">
  <div id="new_bond_panel" class="x_panel">
   <div class="x_title">
    <h2>{% trans 'Bonds with player' %}</h2>
    <ul class="nav navbar-right panel_toolbox">
     <li class="pull-right">
      <a id="bond_with_player_collapse_btn" class="collapse-link" href="#">
       <i class="fa fa-chevron-up"></i>
      </a>
     </li>
    </ul>
    <div class="clearfix"></div>
   </div>
   <div class="x_content">
    <form role="form">
      <div class="form-group">
       <input class="form-control" id="searchinput" type="search" placeholder="Search player…">
      </div>
      <div id="searchlist" class="list-group">
       {% for usr in users %}
        {% ifnotequal usr request.user %}
        <a class="list-group-item" href="{% url 'game:bond' usr %}"><span>{{ usr }}</span></a>
        {% endifnotequal %}
       {% endfor %}
      </div>
    </form>
   </div>
  </div>
 </div>
</div>

<div class="row">
 <div class="col-md-6 col-sm-6 col-xs-12">
  <div id="bonds_panel" class="x_panel">
   <div class="x_title">
    <h2>{% trans 'Bonds as borrower' %} ({{ as_borrower_bonds.count }}) <small>{% trans 'Bonds you need to pay' %}</small></h2>
    <ul class="nav navbar-right panel_toolbox">
     <li class="pull-right">
      <a id="received_bond_collapse_btn" class="collapse-link" href="#">
       <i class="fa fa-chevron-up"></i>
      </a>
     </li>
    </ul>
    <div class="clearfix"></div>
   </div>
   <div class="x_content">
   {% blocktrans %}You can negotiate a bond you need to pay by putting the
   bond number “Bond #” when offering a new exchange.
   That way, you offer to pass the payment responsibility to the other player.
   {% endblocktrans %}
   </div>
   <div class="x_content">
     <table class="table table-hover">
      </thead>
       <tr>
        <th>Bond #</th>
        <th>{% trans 'Holder' %}</th>
        <th>{% trans 'Status' %}</th>
        <th>{% trans 'Content' %}</th>
       </tr>
      </thead>
      <tbody>
       {% for b in as_borrower_bonds %}
       <tr data-toggle="collapse" data-target="#borrower_bond_detail_{{ b.pk }}" class="accordion-toggle">
        <td>
         {{ b.pk }}
        </td>
        <td>{{ b.holder }}</td>
        <td>
         {% if b.is_pending %}
         <span class="label label-primary">{% trans 'Pending' %}</span>
          {% if b.is_payable %}
          <span class="label label-info">{% trans 'Payable' %}</span>
          {% else %}
          <span class="label label-default">{% trans 'Cannot pay' %}</span>
          {% endif %}
         {% elif b.is_paid %}
         <span class="label label-success">{% trans 'Paid' %}</span>
         {% elif b.is_forgiven %}
         <span class="label label-default">{% trans 'Forgiven' %}</span>
         {% endif %}
        </td>
        <td>
         {% if b.includes_currency %}
         <i class="fa fa-money" title="{% trans 'Currency' %}"></i>
         {% endif %}
         {% if b.includes_agricultural %}
         <i class="fa fa-tree" title="{% trans 'Agricultural Goods' %}"></i>
         {% endif %}
         {% if b.includes_manufactured %}
         <i class="fa fa-gears" title="{% trans 'Manufactured Goods' %}"></i>
         {% endif %}
         {% if b.includes_territory %}
         <i class="fa fa-flag" title="{% trans 'Territory' %}"></i>
         {% endif %}
        </td>
       </tr>
        <tr>
         <td colspan="12" class="hiddenRow">
          <div class="accordian-body collapse" id="borrower_bond_detail_{{ b.pk }}">
          <small>
           <table class="table table-hover">
            </thead>
             <tr>
              <th></th>
              <th>Payment</th>
             </tr>
            </thead>
            <tbody>
             {% if b.includes_currency %}
             <tr>
              <th>{% trans 'Currency:' %}</th>
              <td>{{ b.resources.currency }}</td>
             </tr>
             {% endif %}
             {% if b.includes_manufactured %}
             <tr>
              <th>{% trans 'Manufactured Goods:' %}</th>
              <td>{{ b.resources.manufactured }}</td>
             </tr>
             {% endif %}
             {% if b.includes_agricultural %}
             <tr>
              <th>{% trans 'Agricultural Goods:' %}</th>
              <td>{{ b.resources.agricultural }}</td>
             </tr>
             {% endif %}
             {% if b.includes_territory %}
             <tr>
              <th>{% trans 'Territory:' %}</th>
              <td>{% if b.territory %}{{ b.territory.name }} ({{ b.territory.owner.username }}){% endif %}</td>
             </tr>
             {% endif %}
            </tbody>
           </table>
          </small>
          {% if b.get_creation_date %}
           {% to_game_date b.get_creation_date as offerdate %}
           <p>
            {% trans 'Created in ' %}{{ offerdate|date:"M d, Y" }}{% if b.is_paid %}{% to_game_date b.get_payment_date as answerdate %}{% trans ', paid in ' %}{{ answerdate|date:"M d, Y" }}{% endif %}{% if b.is_forgiven %}{% trans ', but it has been forgiven.' %}{% endif %}.
           </p>
          {% endif %}
          {% if b.is_pending and b.is_payable %}
          <form action="{% url 'game:update_bond' b.pk %}" method="post" role="form">
           {% csrf_token %}
           <button type="submit" name="pay" class="btn btn-round btn-success btn-xs">{% trans 'Pay' %}</button>
          </form>
          {% endif %}
          </div>
         </td>
        </tr>
       {% endfor %}
      </tbody>
     </table>
   </div>
  </div>
 </div>
</div>


<div class="row">
 <div class="col-md-6 col-sm-6 col-xs-12">
  <div id="bonds_panel" class="x_panel">
   <div class="x_title">
    <h2>{% trans 'Bonds as holder' %} ({{ as_holder_bonds.count }}) <small>{% trans 'You will receive these payments' %}</small></h2>
    <ul class="nav navbar-right panel_toolbox">
     <li class="pull-right">
      <a class="collapse-link" href="#">
       <i class="fa fa-chevron-up"></i>
      </a>
     </li>
    </ul>
    <div class="clearfix"></div>
   </div>
   <div class="x_content">
     <table class="table table-hover">
      </thead>
       <tr>
        <th>Bond #</th>
        <th>{% trans 'Borrower' %}</th>
        <th>{% trans 'Status' %}</th>
        <th>{% trans 'Content' %}</th>
       </tr>
      </thead>
      <tbody>
       {% for b in as_holder_bonds %}
       <tr data-toggle="collapse" data-target="#holder_bond_detail_{{ b.pk }}" class="accordion-toggle">
        <td>
         {{ b.pk }}
        </td>
        <td>{{ b.borrower }}</td>
        <td>
         {% if b.is_pending %}
         <span class="label label-primary">{% trans 'Pending' %}</span>
          {% if b.is_payable %}
          <span class="label label-info">{% trans 'Can be paid' %}</span>
          {% else %}
          <span class="label label-default">{% trans 'Cannot be paid' %}</span>
          {% endif %}
         {% elif b.is_paid %}
         <span class="label label-success">{% trans 'Paid' %}</span>
         {% elif b.is_forgiven %}
         <span class="label label-default">{% trans 'Forgiven' %}</span>
         {% endif %}
        </td>
        <td>
         {% if b.includes_currency %}
         <i class="fa fa-money" title="{% trans 'Currency' %}"></i>
         {% endif %}
         {% if b.includes_agricultural %}
         <i class="fa fa-tree" title="{% trans 'Agricultural Goods' %}"></i>
         {% endif %}
         {% if b.includes_manufactured %}
         <i class="fa fa-gears" title="{% trans 'Manufactured Goods' %}"></i>
         {% endif %}
         {% if b.includes_territory %}
         <i class="fa fa-flag" title="{% trans 'Territory' %}"></i>
         {% endif %}
        </td>
       </tr>
        <tr>
         <td colspan="12" class="hiddenRow">
          <div class="accordian-body collapse" id="holder_bond_detail_{{ b.pk }}">
          <small>
           <table class="table table-hover">
            </thead>
             <tr>
              <th></th>
              <th>Payment</th>
             </tr>
            </thead>
            <tbody>
             {% if b.includes_currency %}
             <tr>
              <th>{% trans 'Currency:' %}</th>
              <td>{{ b.resources.currency }}</td>
             </tr>
             {% endif %}
             {% if b.includes_manufactured %}
             <tr>
              <th>{% trans 'Manufactured Goods:' %}</th>
              <td>{{ b.resources.manufactured }}</td>
             </tr>
             {% endif %}
             {% if b.includes_agricultural %}
             <tr>
              <th>{% trans 'Agricultural Goods:' %}</th>
              <td>{{ b.resources.agricultural }}</td>
             </tr>
             {% endif %}
             {% if b.includes_territory %}
             <tr>
              <th>{% trans 'Territory:' %}</th>
              <td>{% if b.territory %}{{ b.territory.name }} ({{ b.territory.owner }}){% endif %}</td>
             </tr>
             {% endif %}
            </tbody>
           </table>
          </small>
          {% if b.get_creation_date %}
           {% to_game_date b.get_creation_date as offerdate %}
           <p>
            {% trans 'Created in ' %}{{ offerdate|date:"M d, Y" }}{% if b.is_paid %}{% to_game_date b.get_payment_date as answerdate %}{% trans ', paid in ' %}{{ answerdate|date:"M d, Y" }}{% endif %}{% if b.is_forgiven %}{% trans ', but it has been forgiven.' %}{% endif %}.
           </p>
          {% endif %}
          {% if b.is_pending %}
          <form action="{% url 'game:update_bond' b.pk %}" method="post" role="form">
           {% csrf_token %}
           <button type="submit" name="forgive" class="btn btn-round btn-warning btn-xs">{% trans 'Forgive' %}</button>
          </form>
          {% endif %}
          </div>
         </td>
        </tr>
       {% endfor %}
      </tbody>
     </table>
   </div>
  </div>
 </div>
</div>
{% endblock %}

{% block append_script %}
<script src="{% static 'game/js/bootstrap-list-filter.min.js' %}"></script>
<script src="{% static 'game/js/knob/jquery.knob.min.js' %}"></script>
<script src="{% static 'game/js/icheck.min.js' %}"></script>
<script src="{% static 'game/js/jquery.sparklinb.min.js' %}"></script>
<script>
$('#searchlist').btsListFilter('#searchinput', {itemChild: 'span'});

function newbond() {
  $('#new_bond_tooltip').mouseout();
  $('#new_bond_panel').show();
  $('#new_bond_btn').hide();
}

$('#bond_with_player_collapse_btn').click();

$('#filter_bonds').click(function() {
 var opts = '';
 if ($('input[name="filter_opts_pending"]').filter(':checked').val()) {
  opts += 'W';
 }
 if ($('input[name="filter_opts_paid"]').filter(':checked').val()) {
  opts += 'P';
 }
 if ($('input[name="filter_opts_forgiven"]').filter(':checked').val()) {
  opts += 'F';
 }
 document.location = "{% url 'game:filter_bonds_without_opts'  %}" + opts;
});

</script>
{% endblock %}